# markdownlint configuration
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD013 - Line length
MD013:
  line_length: 200
  heading_line_length: 100
  code_block_line_length: 200
  tables: false

# MD024 - Multiple headings with the same content
MD024:
  siblings_only: true

# MD033 - Inline HTML (allow for badges, etc.)
MD033:
  allowed_elements:
    - br
    - details
    - summary
    - img
    - a

# MD041 - First line should be a heading
MD041: false

# MD046 - Code block style
MD046:
  style: fenced
