# yamllint configuration
# See: https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  # Allow long lines (GitHub Actions often have long expressions)
  line-length:
    max: 200
    level: warning

  # GitHub Actions uses ${{ }} expressions that look like brackets
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Allow document start without ---
  document-start: disable

  # Be lenient with comments
  comments:
    min-spaces-from-content: 1

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Truthy values - GitHub Actions uses 'on' as a key
  truthy:
    allowed-values: ["true", "false", "on"]
    check-keys: false
